css ve index hazırlandı
Cutting-Edge-Developers/code-ve-ceza pull request #19
Opened 2022-07-26 02:00 UTC by yunusemredeniz

2022-07-26 08:22 UTC, enesoeztekin requested changes

2022-07-26 08:22 UTC, enesoeztekin commented on index.html
> +            <h6 class="yerleştir">© 2018 - 2022 Ozone Networks, Inc</h6>
Class ismine türkçe karakter girilmiş. Bu da CSS tarafında sorun yaratacaktır.

2022-07-26 08:22 UTC, enesoeztekin commented on src/css/components/footer.css
> +.yerleştir{
CSS dosyasında türkçe karakter kullanımından dolayı kod parçası çalışmayacaktır.

2022-07-26 08:22 UTC, enesoeztekin commented on index.html
> +    <div class="main">
Footer'ın kapsayıcısı olarak semantic HTML etiketlerinden ` <footer>` kullanımı daha doğru olabilirdi.

2022-07-26 09:18 UTC, ziarparvaiz reviewed
Enes'in isaret ettigi yerler dogru turkce class isimlari var ve semantic tag gibi renkleri degiskenlerimiz vardi onu kullanmaliydin `helper.css` dosyadan bakabilirsin
en onemlisi main branchte yapmissin kendini bir branch olusturman lazimdi orda yapip gonderecektin

2022-07-27 15:46 UTC, yunusemredeniz commented on index.html
> +            <h6 class="yerleştir">© 2018 - 2022 Ozone Networks, Inc</h6>
duzeltim :)

2022-07-28 18:31 UTC, celik-arda reviewed
Yazıların ve başlıkların boyutlarının tekrardan ayarlanması gerekiyor, arkaplan rengi mavi  olarak kalmış. Belki arkaplanı helper.css teki uygun siyah renk koduyla `var(--ornekdeger)` şeklinde değiştirebilirsin. Bir de hala bir iki yerde türkçe karakter gördüm, bunlar düzeltilebilir. ctrl + F ile türkçe karakterler silinebilir.   Yine de genel anlamda uğraşılmış. ve emek harcanmış. **Biraz düzeltmeyle harika olacağına eminim.. eline sağlık, teşekkürler.**

2022-07-28 18:32 UTC, merged